import { i18n } from 'src/utils/core/MTXStrings';

export const string = {
  // TODO: Move these to shared/strings when we have all changes of Dambert related to refactor
  appName: i18n.t('app-name'),
  // TODO END
  cancelAccountCompleteSecondSectionText1: i18n.t('cancelAccountComplete.second-section-text-1'),
  cancelAccountCompleteSecondSectionText3: i18n.t('cancelAccountComplete.second-section-text-3'),
  cancelAccountCompleteSecondSectionText2: i18n.t('cancelAccountComplete.second-section-text-2'),
  cancelAccountCompleteFirstSectionTitle: i18n.t('cancelAccountComplete.first-section-title'),
  cancelAccountCompleteSecondSectionTitle: i18n.t('cancelAccountComplete.second-section-title'),
  cancelAccountCompleteThirdSectionText1: i18n.t('cancelAccountComplete.third-section-text-1'),
  cancelAccountCompleteThirdSectionText2: i18n.t('cancelAccountComplete.third-section-text-2'),
  cancelAccountCompleteThirdSectionText3: i18n.t('cancelAccountComplete.third-section-text-3'),
  cancelAccountCompleteHeader: i18n.t('cancelAccountComplete.header'),
  cancelAccountCompleteTitle: i18n.t('cancelAccountComplete.title'),
  cancelAccountCompleteSubtitle: i18n.t('cancelAccountComplete.subtitle'),
  cancelAccountCompleteChatButton: i18n.t('cancelAccountComplete.chat-button'),
  cancelAccontCompletePaymentButton: i18n.t('cancelAccountComplete.payment-button'),
  cancelAccountCompleteContinueButton: i18n.t('cancelAccountComplete.continue-button'),
  cancelAccountSurveyModalTitle: i18n.t('cancelAccount.survey.modal.title'),
  cancelAccountSurveyModalSubtitle1: i18n.t('cancelAccount.survey.modal.subtitle-1'),
  cancelAccountSurveyModalSubtitle2: i18n.t('cancelAccount.survey.modal.subtitle-2'),
  cancelAccountSurveyModalTextTitle: i18n.t('cancelAccount.survey.modal.text-title'),
  cancelAccountSurveyModalTextSubtitle: i18n.t('cancelAccount.survey.modal.text-subtitle'),
  cancelAccountSurveyModalCheckboxInfo: i18n.t('cancelAccount.survey.modal.checkbox-info'),
  cancelAccountSurveyModalBtnCancelAccount: i18n.t('cancelAccount.survey.modal.btnCancelAccount'),
  cancelAccountHeader: i18n.t('cancelAccount.header'),
  cancelAccountSurveyTitle: i18n.t('cancelAccount.survey.title'),
  cancelAccountSurveySubtitle: i18n.t('cancelAccount.survey.subtitle'),
  cancelAccountSurveyQuestion: i18n.t('cancelAccount.survey.question'),
  cancelAccountSurveyOption4Title: i18n.t('cancelAccount.survey.option-4-title'),
  cancelAccountSurveyOption4Placeholder: i18n.t('cancelAccount.survey.option-4-placeholder'),
  cancelAccountSurveyContinueButton: i18n.t('cancelAccount.survey.continue-button'),
  cancelAccountSurveyOption1: i18n.t('cancelAccount.survey.option-1'),
  cancelAccountSurveyOption2: i18n.t('cancelAccount.survey.option-2'),
  cancelAccountSurveyOption3: i18n.t('cancelAccount.survey.option-3'),
  cancelAccountSurveyOption4: i18n.t('cancelAccount.survey.option-4'),
  cancelAccountWaitingErrorTitle: i18n.t('cancel-account-waiting.errorTitle'),
  cancelAccountWaitingErrorSubtitle: i18n.t('cancel-account-waiting.errorSubtitle'),
  cancelAccountWaitingErrorDescription: i18n.t('cancel-account-waiting.errorDescription'),
  cancelAccountWaitingErrorButtonLabel: i18n.t('cancel-account-waiting.errorButtonLabel'),
  cancelAccountWaitingWaitingTitle: i18n.t('cancel-account-waiting.waiting-title'),
  cancelAccountWaitingWaitingSubtitle1: i18n.t('cancel-account-waiting.waiting-subtitle-1'),
  cancelAccountWaitingWaitingSubtitle2: i18n.t('cancel-account-waiting.waiting-subtitle-2'),
  cancelAccountWaitingWaitingErrorTitle: i18n.t('cancel-account-waiting.errorTitle'),
  cancelAccountWaitingWaitingErrorSubtitle: i18n.t('cancel-account-waiting.errorSubtitle'),
  cancelAccountWaitingWaitingErrorDescription: i18n.t('cancel-account-waiting.errorDescription'),
  cancelAccountWaitingWaitingErrorButtonLabel: i18n.t('cancel-account-waiting.errorButtonLabel'),
  cancelAccountTitle: i18n.t('cancelAccount.title'),
  cancelAccountSubtitle1: i18n.t('cancelAccount.subtitle1'),
  cancelAccountSubtitle2: i18n.t('cancelAccount.subtitle2'),
  cancelAccountQuestionLabel: i18n.t('cancelAccount.question-label'),
  cancelAccountContinueButton: i18n.t('cancelAccount.continue-button'),
};
