import { AuthRoutesEnum } from 'src/shared/enums/routes/auth-routes.enum';
import navigationScreenNames from './navigationScreenNames';
import { ScreenClassType } from './types';

const navigationScreenClasses: Record<string, ScreenClassType> = {
  Profile: {
    tipoZona: 'Perfil',
    zona: 'Inicio',
    subZona: 'VerPerfil',
    seccion: '(not available)',
  },
  ProfileCard: {
    tipoZona: 'Perfil',
    zona: 'Inicio',
    subZona: 'InfoTarjeta',
    seccion: '(not available)',
  },
  HomeProfile: {
    tipoZona: 'Perfil',
    zona: 'Inicio',
    subZona: 'Configuracion',
    seccion: '(not available)',
  },
  [navigationScreenNames.home]: {
    tipoZona: 'Home',
    zona: 'Inicio',
    subZona: '(not available)',
    seccion: '(not available)',
  },
  [AuthRoutesEnum.SIGN_IN]: {
    tipoZona: 'Login',
    zona: 'InicioSesion',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.getEmail]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.getDni]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.passwordVerification]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'CreaClave',
    seccion: '(not available)',
  },
  [navigationScreenNames.passwordRepeat]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'RepiteClave',
    seccion: '(not available)',
  },
  [navigationScreenNames.getPhone]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'Celular',
    seccion: '(not available)',
  },
  VerifyOTPRegister: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'OTP',
    seccion: '(not available)',
  },
  [navigationScreenNames.offerUnavailable]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'NoHayLead',
    seccion: '(not available)',
  },
  [navigationScreenNames.startDocumentValidation]: {
    tipoZona: 'Login',
    zona: 'Registrarse',
    subZona: 'Final',
    seccion: '(not available)',
  },
  [navigationScreenNames.recoveryPassword.getDNI]: {
    tipoZona: 'Login',
    zona: 'RecuperarContrasena',
    subZona: 'RecuperaClave',
    seccion: '(not available)',
  },
  VerifyOTPRecovery: {
    tipoZona: 'Login',
    zona: 'RecuperarContrasena',
    subZona: 'Verificacion',
    seccion: '(not available)',
  },
  [navigationScreenNames.recoveryPassword.newPassword]: {
    tipoZona: 'Login',
    zona: 'RecuperarContrasena',
    subZona: 'Recuperar',
    seccion: '(not available)',
  },
  [navigationScreenNames.recoveryPassword.response]: {
    tipoZona: 'Login',
    zona: 'RecuperarContrasena',
    subZona: 'Final',
    seccion: '(not available)',
  },
  [navigationScreenNames.introductionDocumentScan]: {
    tipoZona: 'ValidacionDni',
    zona: 'Inicio',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.getDocumentFront]: {
    tipoZona: 'ValidacionDni',
    zona: 'FrenteDNI',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.documentFrontPreview]: {
    tipoZona: 'ValidacionDni',
    zona: 'FrenteDNI',
    subZona: 'ModalVerifica',
    seccion: '(not available)',
  },
  [navigationScreenNames.getDocumentReverse]: {
    tipoZona: 'ValidacionDni',
    zona: 'ReversoDNI',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.documentReversePreview]: {
    tipoZona: 'ValidacionDni',
    zona: 'ReversoDNI',
    subZona: 'ModalVerifica',
    seccion: '(not available)',
  },
  ModalCargandoReverso: {
    tipoZona: 'ValidacionDni',
    zona: 'ReversoDNI',
    subZona: 'ModalCargandoReverso',
    seccion: '(not available)',
  },
  [navigationScreenNames.documentValidationLoading]: {
    tipoZona: 'ValidacionDni',
    zona: 'SubiendoDocumento',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  DocumentValidationInProcess: {
    tipoZona: 'ValidacionDni',
    zona: 'ValidandoDNI',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.manualCheck]: {
    tipoZona: 'ValidacionDni',
    zona: 'ValidandoDNI',
    subZona: 'DobleVerificacion',
    seccion: '(not available)',
  },
  [navigationScreenNames.validationResponse]: {
    tipoZona: 'ValidacionDni',
    zona: 'Final',
    subZona: '(not available)',
    seccion: '(not available)',
  },
  [navigationScreenNames.livenessIntro]: {
    tipoZona: 'ValidacionRostro',
    zona: 'Inicio',
    subZona: '(not available)',
    seccion: '(not available)',
  },
  [navigationScreenNames.livenessFaceScan]: {
    tipoZona: 'ValidacionRostro',
    zona: 'Grabacion',
    subZona: 'Inicio',
    seccion: '(not available)',
  },
  LivenessCapture: {
    tipoZona: 'ValidacionRostro',
    zona: 'Grabacion',
    subZona: 'Captura',
    seccion: '(not available)',
  },
  LivenessEnd: {
    tipoZona: 'ValidacionRostro',
    zona: 'Grabacion',
    subZona: 'Final',
    seccion: '(not available)',
  },
  [navigationScreenNames.livenessLoading]: {
    tipoZona: 'ValidacionRostro',
    zona: 'Validacion',
    subZona: 'Subiendo',
    seccion: '(not available)',
  },
  LivenessUploadError: {
    tipoZona: 'ValidacionRostro',
    zona: 'Validacion',
    subZona: 'Subiendo',
    seccion: 'ModalError',
  },
  LivenessValidationInProcess: {
    tipoZona: 'ValidacionRostro',
    zona: 'Validacion',
    subZona: 'Validando',
    seccion: '(not available)',
  },
  [navigationScreenNames.livenessGoToGetPersonalData]: {
    tipoZona: 'ValidacionRostro',
    zona: 'Validacion',
    subZona: 'Final',
    seccion: '(not available)',
  },
  [navigationScreenNames.getPersonalData]: {
    tipoZona: 'DatosExtras',
    zona: 'DatosPersonales',
    subZona: 'Domicilio',
    seccion: '(not available)',
  },
  [navigationScreenNames.getWorkData]: {
    tipoZona: 'DatosExtras',
    zona: 'DatosPersonales',
    subZona: 'Ocupacion',
    seccion: '(not available)',
  },
  [navigationScreenNames.getPublicWorkConfirmation]: {
    tipoZona: 'DatosExtras',
    zona: 'DatosPersonales',
    subZona: 'Funciones',
    seccion: '(not available)',
  },
  [navigationScreenNames.personalDataComplete]: {
    tipoZona: 'DatosExtras',
    zona: 'RegistroCompletado',
    subZona: 'Final',
    seccion: '(not available)',
  },
  ModalOfferLoading: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'ModalInicio',
    seccion: '(not available)',
  },
  [navigationScreenNames.cardOfferDetails]: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'Informacion',
    seccion: '(not available)',
  },
  CardOfferMoreDetails: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'InformacionAdicional',
    seccion: '(not available)',
  },
  CardOfferMoreDetails: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'InformacionAdicional',
    seccion: '(not available)',
  },
  CardOfferMoreDetails: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'InformacionAdicional',
    seccion: '(not available)',
  },
  [navigationScreenNames.cardDocuments]: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'Documentos',
    seccion: '(not available)',
  },
  [navigationScreenNames.cardDocumentDetail]: {
    tipoZona: 'OfertaTC',
    zona: 'Detalle',
    subZona: 'Documentos',
    seccion: 'DetalleDocumento',
  },
  ModalOfferValidationLoading: {
    tipoZona: 'OfertaTC',
    zona: 'Validacion',
    subZona: 'ModalCargando',
    seccion: '(not available)',
  },
  ModalOfferError: {
    tipoZona: 'OfertaTC',
    zona: 'Validacion',
    subZona: 'ModalErrorSolicitud',
    seccion: '(not available)',
  },
  ModalOfferError2: {
    tipoZona: 'OfertaTC',
    zona: 'Validacion',
    subZona: 'ModalErrorSolicitud2',
    seccion: '(not available)',
  },
  [navigationScreenNames.cardOfferComplete]: {
    tipoZona: 'OfertaTC',
    zona: 'OfertaSeleccionada',
    subZona: 'Final',
    seccion: '(not available)',
  },
  BenefitsList: {
    tipoZona: 'Beneficios',
    zona: 'VerBeneficios',
    subZona: 'ListaBeneficios',
    seccion: '(not available)',
  },
  [navigationScreenNames.genericError]: {
    tipoZona: 'Error',
    zona: 'Generico',
    subZona: '(not available)',
    seccion: '(not available)',
  },
};

export default navigationScreenClasses;
