import { i18n } from 'src/utils/core/MTXStrings';

export const string = {
  activateCardResponseErrorTitle: i18n.t('requestCard:activate-card-response.errorTitle'),
  activateCardResponseErrorSubtitle: i18n.t('requestCard:activate-card-response.errorSubtitle'),
  activateCardResponseErrorDescription: i18n.t('requestCard:activate-card-response.errorDescription'),
  activateCardResponseErrorButtonLabel: i18n.t('requestCard:activate-card-response.errorButtonLabel'),
  activateCardTitle: i18n.t('requestCard:activate-card.title'),
  activateCardDescription: i18n.t('requestCard:activate-card.description'),
  activateCardInputError: i18n.t('requestCard:activate-card.inputError'),
  activateCardSubmit: i18n.t('requestCard:activate-card.submit'),
  activateCardResponseTitle: i18n.t('requestCard:activate-card-response.title'),
  activateCardResponseSubtitle: i18n.t(
    'requestCard:activate-card-response.subTitle',
  ),
  activateCardResponseMessageBold: i18n.t('requestCard:activate-card-response.message-bold'),
  activateCardResponseMessage: i18n.t('requestCard:activate-card-response.message'),
  activateCardResponseSubmit: i18n.t('requestCard:activate-card-response.submit'),
  cardInfoActive: i18n.t('requestCard:card-info.active'),
  cardInfoInactive: i18n.t('requestCard:card-info.inactive'),
  cardInfoPending: i18n.t('requestCard:card-info.pending'),
  cardInfoPendingActivate: i18n.t('requestCard:card-info.pending-activate'),
  cardInfoTitle: i18n.t('requestCard:card-info.title'),
  cardInfoDescription1: i18n.t('requestCard:card-info.description-1'),
  cardInfoMessagePending1: i18n.t('requestCard:card-info.message-pending-1'),
  cardInfoMessagePendingBold: i18n.t('requestCard:card-info.message-pending-bold'),
  cardInfoMessagePending2: i18n.t('requestCard:card-info.message-pending-2'),
  cardInfoMessageActive: i18n.t('requestCard:card-info.message-active'),
  cardInfoMessageInactive: i18n.t('requestCard:card-info.message-inactive'),
  cardInfoChangePinButtonText: i18n.t('requestCard:card-info.change-pin.button-text'),
  cardInfoChangePinButtonDetail: i18n.t('requestCard:card-info.change-pin.button-detail'),
  cardInfoChangePinForgotPinButtonText: i18n.t('requestCard:card-info.change-pin.forgot-pin-button'),
  changePingChangeErrorTitle: i18n.t('requestCard:change-pin.change-error.title'),
  changePinChangeErrorSubTitle: i18n.t('requestCard:change-pin.change-error.sub-title'),
  changePinChangeErrorMessage: i18n.t('requestCard:change-pin.change-error.message'),
  changePinChangeErrorSubmit: i18n.t('requestCard:change-pin.change-error.submit'),
  changePinChangeSuccessTitle: i18n.t('requestCard:change-pin.change-success.title'),
  changePinChangeSuccessSubTitleAfterActivation: i18n.t(
    'requestCard:change-pin.change-success.sub-title-after-activation',
  ),
  changePinChangeSuccessSubTitle: i18n.t('requestCard:change-pin.change-success.sub-title'),
  changePinChangeSuccessMessage: i18n.t('requestCard:change-pin.change-success.message'),
  changePinChangeSuccessSubmit: i18n.t('requestCard:change-pin.change-success.submit'),
  requestCardLocationFormDepartmentLabel: i18n.t('requestCard:request-card.locationForm.department-label'),
  requestCardLocationFormProvinceLabel: i18n.t('requestCard:request-card.locationForm.province-label'),
  requestCardLocationFormDistrictLabel: i18n.t('requestCard:request-card.locationForm.district-label'),
  requestCardLocationFormAddressLabel: i18n.t('requestCard:request-card.locationForm.address-label'),
  requestCardLocationFormAddressPlaceholder: i18n.t(
    'requestCard:request-card.locationForm.address-placeholder',
  ),
  requestCardLocationFormReferenceLabel: i18n.t('requestCard:request-card.locationForm.reference-label'),
  requestCardLocationFormReferencePlaceholder: i18n.t(
    'requestCard:request-card.locationForm.reference-placeholder',
  ),
  requestCardUseFormSubmitModal: i18n.t('requestCard:request-card.userForm.submitModal'),
  changePinSdkErrorModalTitle: i18n.t('requestCard:change-pin.sdk-error-modal.title'),
  changePinSdkErrorModalSubtitle: i18n.t('requestCard:change-pin.sdk-error-modal.subtitle'),
  changePinSdkErrorModalButtonClose2: i18n.t('requestCard:change-pin.sdk-error-modal.button-close-2'),
  changePinSdkErrorModalButtonClose: i18n.t('requestCard:change-pin.sdk-error-modal.button-close'),
  changePinForgotPinModalTitle: i18n.t('requestCard:change-pin.forgot-pin-modal.title'),
  changePinForgotPinModalSubtitle: i18n.t('requestCard:change-pin.forgot-pin-modal.subtitle'),
  changePinForgotPinModalButton: i18n.t('requestCard:change-pin.forgot-pin-modal.button'),
  changePinForgotPinModalButtonClose: i18n.t('requestCard:change-pin.forgot-pin-modal.button-close'),
  physicalCardInactiveVirtualCardModalTitle: i18n.t(
    'requestCard:physical-card.inactive-virtual-card-modal.title',
  ),
  changePinInactivePhysicalCardModalTitle: i18n.t('requestCard:change-pin.inactive-physical-card-modal.title'),
  physicalCardInactiveVirtualCardModalSubtitle: i18n.t(
    'requestCard:physical-card.inactive-virtual-card-modal.subtitle',
  ),
  changePinInactivePhysicalCardModalSubtitle: i18n.t(
    'requestCard:change-pin.inactive-physical-card-modal.subtitle',
  ),
  changePinInactivePhysicalCardModalButtonConfig: i18n.t(
    'requestCard:change-pin.inactive-physical-card-modal.button-config',
  ),
  changePinInactivePhysicalCardModalButtonClose: i18n.t(
    'requestCard:change-pin.inactive-physical-card-modal.button-close',
  ),
  physicalCardOrderStatusTitleInfo: i18n.t('requestCard:physical-card.order-status.title-info'),
  physicalCardOrderStatusTitleSchedule: i18n.t('requestCard:physical-card.order-status.title-schedule'),
  requestCardPhoneFormLabel: i18n.t('requestCard:request-card.phoneForm.label'),
  requestCardPhoneFormTitle: i18n.t('requestCard:request-card.phoneForm.title'),
  requestCardAddressFormTitle: i18n.t('requestCard:request-card.addressForm.title'),
  requestCardPhoneFormPlaceholder: i18n.t('requestCard:request-card.phoneForm.placeholder'),
  physicalCardFirstSlideTitle: i18n.t('requestCard:physical-card.first-slide-title'),
  physicalCardFirstSlideText: i18n.t('requestCard:physical-card.first-slide-text'),
  physicalCardSecondSlideTitle: i18n.t('requestCard:physical-card.second-slide-title'),
  physicalCardSecondSlideText: i18n.t('requestCard:physical-card.second-slide-text'),
  physicalCardThirdSlideTitle: i18n.t('requestCard:physical-card.third-slide-title'),
  physicalCardThirdSlideText: i18n.t('requestCard:physical-card.third-slide-text'),
  physicalCardTitle: i18n.t('requestCard:physical-card.title'),
  physicalCardButton: i18n.t('requestCard:physical-card.button'),
  physicalCardOrderStatusTitle: i18n.t('requestCard:physical-card.order-status.title'),
  physicalCardOrderStatusButton: i18n.t('requestCard:physical-card.order-status.button'),
  requestCardErrorScheduleUnavailableTitle: i18n.t('requestCard:request-card.error.schedule-unavailable-title'),
  requestCardErrorScheduleUnavailableSubtitle: i18n.t(
    'requestCard:request-card.error.schedule-unavailable-subtitle',
  ),
  requestCardErrorScheduleUnavailableDescription: i18n.t(
    'requestCard:request-card.error.schedule-unavailable-description',
  ),
  requestCardErrorScheduleUnavailableButton: i18n.t('requestCard:request-card.error.schedule-unavailable-button'),
  requestCardIntroductionRequestTitle: i18n.t('requestCard:request-card.introductionRequest.title'),
  requestCardIntroductionRequestDescription: i18n.t('requestCard:request-card.introductionRequest.description'),
  requestCardIntroductionRequestContinue: i18n.t('requestCard:request-card.introductionRequest.continue'),
  requestCardIntroductionRequestCancel: i18n.t('requestCard:request-card.introductionRequest.cancel'),
  requestCardLocationFormTitle: i18n.t('requestCard:request-card.locationForm.title'),
  requestCardLocationFormDescription: i18n.t('requestCard:request-card.locationForm.description'),
  requestCardLocationFormSubtitle: i18n.t('requestCard:request-card.locationForm.subtitle'),
  requestCardLocationFormDepartmentPlaceholder: i18n.t(
    'requestCard:request-card.locationForm.department-placeholder',
  ),
  requestCardLocationFormProvincePlaceholder: i18n.t(
    'requestCard:request-card.locationForm.province-placeholder',
  ),
  requestCardLocationFormDistrictPlaceholder: i18n.t(
    'requestCard:request-card.locationForm.district-placeholder',
  ),
  requestCardLocationFormSubmit: i18n.t('requestCard:request-card.locationForm.submit'),
  requestCardErrorProcessErrorTitle: i18n.t('requestCard:request-card.error.process-error-title'),
  requestCardErrorProcessErrorSubtitle: i18n.t('requestCard:request-card.error.process-error-subtitle'),
  requestCardErrorProcessErrorDescription: i18n.t('requestCard:request-card.error.process-error-description'),
  requestCardErrorProcessErrorButon: i18n.t('requestCard:request-card.error.process-error-button'),
  requestCardDateFormTitle: i18n.t('requestCard:request-card.dateForm.title'),
  requestCardScheduleMessage: i18n.t('requestCard:request-card.schedule.message'),
  requestCardScheduleTitle: i18n.t('requestCard:request-card.schedule.title'),
  requestCardScheduleTitleEditing: i18n.t('requestCard:request-card.schedule.title-editing'),
  requestCardScheduleScheduleTitle: i18n.t('requestCard:request-card.schedule.scheduleTitle'),
  requestCardScheduleinningTitle: i18n.t('requestCard:request-card.schedule.inningTitle'),
  requestCardScheduleinningLabel: i18n.t('requestCard:request-card.schedule.inningLabel'),
  requestCardScheduleWeekTitle: i18n.t('requestCard:request-card.schedule.weekTitle'),
  requestCardDateformSubmit: i18n.t('requestCard:request-card.dateForm.submit'),
  requestCardSumaryTitle: i18n.t('requestCard:request-card.sumary.title'),
  requestCardumaryDescription: i18n.t('requestCard:request-card.sumary.description'),
  requestCardSumarySubtitleUserData: i18n.t('requestCard:request-card.sumary.subTitleUserData'),
  requestCardSumarySubtitleSchedule: i18n.t('requestCard:request-card.sumary.subTitleSchedule'),
  requestCardSumarySubmit: i18n.t('requestCard:request-card.sumary.submit'),
  requestCardUseFormTitle: i18n.t('requestCard:request-card.userForm.title'),
  requestCardUserFormSubtitle: i18n.t('requestCard:request-card.userForm.subtitle'),
  requestCardUserFormDescription: i18n.t('requestCard:request-card.userForm.description'),
  requestCardUserFormContactLabel: i18n.t('requestCard:request-card.userForm.contactLabel'),
  requestCardUserFormEdit: i18n.t('requestCard:request-card.userForm.edit'),
  requestCardUserFormAddressLabel: i18n.t('requestCard:request-card.userForm.addressLabel'),
  requestCardUserFormScheduleLabel: i18n.t('requestCard:request-card.userForm.scheduleLabel'),
  requestCardUserFormSubmit: i18n.t('requestCard:request-card.userForm.submit'),
  requestCardUserFormCancel: i18n.t('requestCard:request-card.userForm.cancel'),
};
