import { createTheme } from '@shopify/restyle';
import { RFValue } from 'react-native-responsive-fontsize';

export const colors = {
  splash: '#F1F1F4',
  // Primary
  primaryMedium: '#B8B8B8',
  primaryDarkest: '#0D1332',
  primaryDark: '#000000',
  primaryLigth: '#D1D4E0',
  primary1000: '#000000',
  primary400: '#B8B8B8',
  primary500: '#8F8F8F',
  primary600: '#7B7A7A',
  primary800: '#3D3D3D',
  primary900: '#292929',
  primary700: '#666666',
  primary300: '#CCCCCC',
  primary200: '#E8E8E8',
  primary100: '#F0F0F0',
  primary000: '#ffffff',
  yankeesBlue: '#2B2845',
  green: '#00D27C',
  redError: '#F00505',
  darkBlueGray: '#666A8F',
  ghostWhite: '#FAFBFC',
  white: '#FFFFFF',
  success: '#00CC78',
  disable: '#D1D4E0',
  secundaryDisable: '#F0F1F5',
  // Secondary
  errorMedium: '#D9261F',
  warningMedium: '#ED6625',
  textLink: '#1843AA',
  info: '#D1D5E0',
  // Complementary
  complementaryMint600: '#00CC78',
  // Transaction
  backgroundFailed: '#FCEAE9',
  textFailed: '#D9261F',
  textMethod: '#6E7184',
  backgroundReturn: '#DAF1DF',

  // Variant Scales
  gray400: '#5F6173',
  gray300: '#8084A2',
  gray200: '#A2A6BD',
  gray100: '#C6C9D8',
  gray60: '#DDDFE8',
  gray25: '#EBEDF1',
  gray5: '#F9F9FA',
  // Opacity
  greenWithOpacity: 'rgba(96, 211, 126, 0.2)',
  whiteWithOpacity: 'rgba(250, 251, 252, 0.7)',
  blackWithOpacity: 'rgba(0, 0, 0, 0.8)',
  modalWithOpacity: 'rgba(21, 24, 49, 0.8)',
  modalBlackWithOpacity: 'rgba(0, 0, 0, 0.85)',
  backgroundLabelOpacity: 'rgba(227,235,248,0.5)',
  transparent: 'transparent',
  black: '#11142E',
  feedbackInformativeLight: '#81AAED',
  FeedbackError050: '#FFEBEB',
  FeedbackError100: '#FEC3C3',
  FeedbackError300: '#FC7373',
  FeedbackError600: '#F00505',
  FeedbackSuccess700: '#00A360',
  feedbackInformativeLightest: '#E3EBF8',
  FeedbackWarning600: '#F09405',

  // Gradient
  bottomBackground: 'white',
  topBackground: 'white',

  bottomTabIcon: '#7B7A7A',
  complementaryOcean050: '#ECF6F8',
  complementaryOcean100: '#E1F1F4',

  complementarySteel100: '#E5EBF0',
  complementarySteel900: '#2F3E4B',

  complementaryIndigo050: '#ECEEF9',
  complementaryIndigo100: '#E0E5F5',
  complementaryIndigo200: '#B2BFE6',
  complementaryIndigo500: '#5672C8',
  complementaryIndigo600: '#3C5BB9',
  complementaryIndigo800: '#283D7B',
  complementaryIndigo900: '#1E2D5C',

  complementaryPumpking050: '#FFF2EB',
  complementaryPumpking500: '#FD6E17',
  complementaryPumpkin600: '#F25E02',

  complementaryMint050: '#EBFFF7',
  complementaryMint700: '#00A360',
  complementaryMint900: '#005230',

  complementaryInformative050: '#F0F1FA',
  complementaryInformative600: '#3C5BB9',

  complementaryPrimary100: '#F0F0F0',
  ComplementaryOcean050: '#ECF6F8',

  complementaryOcean200: '#B4DBE4',
  complementaryOcean300: '#96CDD9',
  complementaryOcean500: '#5AB0C4',
  complementaryOcean600: '#419EB4',
  complementaryOcean800: '#2B6A78',
  complementaryOcean900: '#204F5A',
  complementaryCandy500: '#C94C89',
};
export const gradientColors = {
  primary: ['#000000', '#000000'],
  secondary: ['#FFFFFF', '#FFFFFF'],
  danger: ['transparent', 'transparent'],
  disabled: ['#CCCCCC', '#CCCCCC'],
  info: ['rgba(0,0,0,0)', 'rgba(0,0,0,0)'],
  liquidaCard: ['#0E1433', '#545B7E'],
  outline: ['transparent', 'transparent'],
};
export const spacing = {
  'spacing-none': 0,
  'spacing-xxxxxxs': RFValue(1),
  'spacing-xxxxxs': RFValue(2),
  'spacing-xxxxs': RFValue(6),
  'spacing-xxxs': RFValue(4),
  'spacing-xxs': RFValue(8),
  'spacing-xs': RFValue(14),
  'spacing-s': RFValue(16),
  'spacing-sm': RFValue(21),
  'spacing-m': RFValue(24),
  'spacing-xxm': RFValue(28),
  'spacing-xxxm': RFValue(37.5),
  'spacing-xxxxm': RFValue(40),
  'spacing-xm': RFValue(34),
  'spacing-l': RFValue(48),
  'spacing-mmml': RFValue(55),
  'spacing-ml': RFValue(65),
  'spacing-mml': RFValue(70),
  'spacing-xl': RFValue(96),
  'spacing-xxl': RFValue(140),
  'spacing-custom-l': RFValue(127),
};
export const fonts = {
  euclidCircularBold: 'EuclidCircularA-Bold',
  euclidCircularItalic: 'EuclidCircularA-Italic',
  euclidCircularLight: 'EuclidCircularA-Light',
  euclidCircularMedium: 'EuclidCircularA-Medium',
  euclidCircularRegular: 'EuclidCircularA-Regular',
  euclidCircularSemibold: 'EuclidCircularA-SemiBold',

  outfitRegular: 'Outfit-Regular',
  outfitSemibold: 'Outfit-SemiBold',
  outfitBold: 'Outfit-Bold',
  outfitMedium: 'Outfit-Medium',
  robotoSerifMedium: 'RobotoSerif-Medium',
  robotoSerifSemiBold: 'RobotoSerif-SemiBold',
  robotoSerifRegular: 'RobotoSerif-Regular',
};
export const rebrandingTheme = createTheme({
  rebranding: true,
  fonts,
  colors,
  spacing,
  breakpoints: {
    phone: 0,
    tablet: 768,
  },
  textVariants: {
    H1: {
      fontSize: RFValue(32),
      lineHeight: RFValue(36),
      fontFamily: 'EuclidCircularA-Light',
      color: 'black',
    },
    H2: {
      fontSize: RFValue(28),
      lineHeight: RFValue(32),
      fontFamily: 'EuclidCircularA-Light',
      color: 'black',
    },
    H3: {
      fontSize: RFValue(24.5),
      lineHeight: RFValue(28),
      fontFamily: fonts.robotoSerifMedium,
      color: 'black',
    },
    H4: {
      fontSize: RFValue(16),
      fontFamily: fonts.robotoSerifMedium,
      color: 'black',
    },
    Heading: {
      fontSize: RFValue(21),
      fontWeight: '500',
      lineHeight: RFValue(25.2),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading24SemiBold: {
      fontSize: RFValue(21.12),
      lineHeight: RFValue(25.34),
      fontFamily: fonts.robotoSerifSemiBold,
      letterSpacing: 0,
      color: 'black',
    },
    Heading32Medium: {
      fontSize: RFValue(27.5),
      lineHeight: RFValue(33),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading32SemiBold: {
      fontSize: RFValue(27.5),
      lineHeight: RFValue(33),
      fontFamily: fonts.robotoSerifSemiBold,
      letterSpacing: 0,
      color: 'black',
    },

    Heading24Medium: {
      fontSize: RFValue(21),
      lineHeight: RFValue(25.2),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading24pxMedium: {
      fontSize: RFValue(24),
      lineHeight: RFValue(28.8),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading28Medium: {
      fontSize: RFValue(24.64),
      lineHeight: RFValue(29.568),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading28pxMedium: {
      fontSize: RFValue(28),
      lineHeight: RFValue(33.6),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading18Medium: {
      fontSize: RFValue(15.84),
      lineHeight: RFValue(19.008),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading18pxMedium: {
      fontSize: RFValue(18),
      lineHeight: RFValue(21.6),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'primary1000',
      fontWeight: '500',
    },
    Heading24Regular: {
      fontSize: RFValue(21.12),
      lineHeight: RFValue(25.34),
      fontFamily: fonts.robotoSerifRegular,
      letterSpacing: 0,
      color: 'black',
    },
    Heading20SemiBold: {
      fontSize: RFValue(17.6),
      lineHeight: RFValue(21.1),
      fontFamily: fonts.robotoSerifSemiBold,
      letterSpacing: 0,
      color: 'black',
    },
    Heading20Regular: {
      fontSize: RFValue(17.6),
      lineHeight: RFValue(21.1),
      fontFamily: fonts.robotoSerifRegular,
      letterSpacing: 0,
      color: 'black',
    },
    Heading20Medium: {
      fontSize: RFValue(17.6),
      lineHeight: RFValue(21.1),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading20pxMedium: {
      fontSize: RFValue(20),
      lineHeight: RFValue(24),
      fontFamily: fonts.robotoSerifMedium,
      letterSpacing: 0,
      color: 'black',
    },
    Heading18SemiBold: {
      fontSize: RFValue(16.6),
      lineHeight: RFValue(21.1),
      fontFamily: fonts.robotoSerifSemiBold,
      letterSpacing: 0,
      color: 'black',
    },
    Heading18Regular: {
      fontSize: RFValue(16.6),
      lineHeight: RFValue(21.1),
      fontFamily: fonts.robotoSerifRegular,
      letterSpacing: 0,
      color: 'black',
    },
    Link14Medium: {
      fontSize: RFValue(12.25),
      lineHeight: RFValue(17.15),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      color: 'black',
    },
    Link14MediumBlue: {
      fontSize: RFValue(12.25),
      lineHeight: RFValue(17.15),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      color: 'complementaryIndigo600',
      textDecorationLine: 'underline',
    },
    SubTitle: {
      fontSize: RFValue(18),
      lineHeight: RFValue(22),
      fontFamily: fonts.outfitRegular,
      color: 'black',
    },
    SubTitle16: {
      fontSize: RFValue(14.1),
      fontFamily: fonts.outfitRegular,
      lineHeight: RFValue(16.6),
      color: 'black',
    },
    SubTitle18Regular: {
      fontSize: RFValue(15.75),
      lineHeight: RFValue(18.9),
      letterSpacing: 0.16,
      fontFamily: fonts.outfitRegular,
      color: 'primary800',
    },
    SubTitle18pxRegular: {
      fontSize: RFValue(18),
      lineHeight: RFValue(21.6),
      letterSpacing: 0.16,
      fontFamily: fonts.outfitRegular,
      color: 'primary800',
    },
    SubTitle18SemiBold: {
      fontSize: RFValue(18),
      lineHeight: RFValue(21.6),
      fontFamily: fonts.outfitSemibold,
      color: 'black',
    },
    Subtitle24SemiBold: {
      fontSize: RFValue(22),
      lineHeight: RFValue(25.34),
      fontFamily: fonts.outfitSemibold,
    },
    Subtitle24Bold: {
      fontSize: RFValue(22),
      lineHeight: RFValue(28.8),
      fontFamily: fonts.outfitBold,
      letterSpacing: 0.16,
      color: 'black',
    },
    Subtitle20SemiBold: {
      fontSize: RFValue(17.5),
      lineHeight: RFValue(21),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0,
      color: 'black',
    },
    Subtitle20pxSemiBold: {
      fontSize: RFValue(20),
      lineHeight: RFValue(21),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0,
      color: 'black',
    },
    Subtitle20Medium: {
      fontSize: RFValue(17),
      lineHeight: RFValue(24),
      fontFamily: fonts.outfitMedium,
      fontWeight: '500',
      letterSpacing: 0.16,
      color: 'black',
    },
    Subtitle18Bold: {
      fontSize: RFValue(15.75),
      lineHeight: RFValue(18.9),
      letterSpacing: 0.16,
      fontWeight: '700',
      fontFamily: fonts.outfitBold,
      color: 'primaryDark',
    },
    Subtitle18Medium: {
      fontSize: RFValue(15.75),
      lineHeight: RFValue(18.9),
      letterSpacing: 0.16,
      fontFamily: fonts.outfitMedium,
      color: 'primaryDark',
    },
    Subtitle18Regular: {
      fontSize: RFValue(15.75),
      lineHeight: RFValue(18.9),
      letterSpacing: 0.16,
      fontFamily: fonts.outfitRegular,
      color: 'primaryDark',
    },
    SubTitle24: {
      fontSize: RFValue(22),
      fontFamily: fonts.outfitRegular,
      color: 'black',
      lineHeight: RFValue(27.2),
    },
    Subtitle14Semibold: {
      fontSize: RFValue(12),
      lineHeight: RFValue(14.1),
      fontFamily: fonts.outfitSemibold,
      fontWeight: '600',
      color: 'black',
    },
    Subtitle15pxSemibold: {
      fontSize: RFValue(15),
      lineHeight: RFValue(19.2),
      fontFamily: fonts.outfitMedium,
      fontWeight: '600',
      color: 'black',
    },
    Subtitle16Bold: {
      fontSize: RFValue(14),
      lineHeight: RFValue(16.8),
      fontFamily: fonts.outfitBold,
    },
    Subtitle14pxSemibold: {
      fontSize: RFValue(14),
      lineHeight: RFValue(14.1),
      fontFamily: fonts.outfitSemibold,
      fontWeight: '600',
      color: 'black',
    },
    Subtitle16Semibold: {
      fontSize: RFValue(14),
      lineHeight: RFValue(16.8),
      fontFamily: fonts.outfitSemibold,
      fontWeight: '600',
      color: 'black',
    },
    Subtitle16pxSemibold: {
      fontSize: RFValue(16),
      lineHeight: RFValue(19.2),
      fontFamily: fonts.outfitMedium,
      fontWeight: '600',
      color: 'black',
    },
    Subtitle16pxMedium: {
      fontSize: RFValue(14),
      lineHeight: RFValue(16.8),
      fontFamily: fonts.outfitMedium,
      fontWeight: '500',
      color: 'black',
    },
    body: {
      fontSize: RFValue(14),
      lineHeight: RFValue(17.15),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      color: 'black',
    },
    bodySemibold: {
      fontSize: RFValue(12.25),
      lineHeight: RFValue(19),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.16,
      color: 'black',
    },
    body12: {
      fontSize: RFValue(10.5),
      lineHeight: RFValue(14.7),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      color: 'black',
    },
    body12pxRegular: {
      fontSize: RFValue(12),
      lineHeight: RFValue(16.8),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      fontWeight: '400',
    },
    body12Medium: {
      fontSize: RFValue(10.5),
      lineHeight: RFValue(14.7),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      color: 'black',
    },
    body12pxMedium: {
      fontSize: RFValue(12),
      lineHeight: RFValue(16.8),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      fontWeight: '500',
    },
    body12Semibold: {
      fontSize: RFValue(10.5),
      lineHeight: RFValue(14.7),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.16,
      color: 'black',
    },
    body13pxRegular: {
      fontSize: RFValue(13),
      lineHeight: RFValue(18.2),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      color: 'black',
    },
    body13pxSemiBold: {
      fontSize: RFValue(13),
      lineHeight: RFValue(16),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.16,
      color: 'black',
      fontWeight: '600',
    },
    body13Regular: {
      fontSize: RFValue(11.375),
      lineHeight: RFValue(15.925),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      color: 'black',
    },
    body13Medium: {
      fontSize: RFValue(11.375),
      lineHeight: RFValue(15.925),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      fontWeight: '500',
      color: 'black',
    },
    body13pxMedium: {
      fontSize: RFValue(13),
      lineHeight: RFValue(18.2),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      fontWeight: '500',
    },
    body13SemiBold: {
      fontSize: RFValue(11.375),
      lineHeight: RFValue(15.925),
      fontWeight: '600',
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.16,
      color: 'black',
    },
    body14pxRegular: {
      fontSize: RFValue(14),
      lineHeight: RFValue(19),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      color: 'primaryDarkest',
    },
    body14Regular: {
      fontSize: RFValue(12.25),
      lineHeight: RFValue(17.15),
      fontFamily: fonts.outfitRegular,
      letterSpacing: 0.16,
      color: 'primaryDarkest',
    },
    body14SemiBold: {
      fontSize: RFValue(12),
      lineHeight: RFValue(19),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.16,
      color: 'black',
    },
    body14Medium: {
      fontSize: RFValue(12),
      lineHeight: RFValue(19),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      color: 'black',
    },
    body14pxMedium: {
      fontSize: RFValue(14),
      lineHeight: RFValue(19),
      fontFamily: fonts.outfitMedium,
      letterSpacing: 0.16,
      color: 'black',
    },
    Link14SemiBold: {
      fontSize: RFValue(12),
      lineHeight: RFValue(19),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.16,
      color: 'black',
      textDecorationLine: 'underline',
    },
    link: {
      fontSize: RFValue(13),
      fontFamily: fonts.outfitRegular,
      color: 'complementaryIndigo600',
      textDecorationLine: 'underline',
    },
    defaults: {
      fontSize: RFValue(16),
      lineHeight: RFValue(20),
      fontFamily: 'EuclidCircularA-Light',
      color: 'black',
    },
    label: {
      fontSize: RFValue(14),
      fontFamily: fonts.outfitSemibold,
      letterSpacing: 0.35,
      lineHeight: RFValue(16.8),
      color: 'black',
    },
    SubHead: {
      fontSize: RFValue(12),
      lineHeight: RFValue(14),
      fontFamily: 'EuclidCircularA-Light',
      color: 'black',
    },
    subContentBody: {
      fontSize: RFValue(12),
      lineHeight: RFValue(14),
      fontFamily: 'EuclidCircularA-Regular',
      color: 'primaryDarkest',
      opacity: 0.6,
    },
    chipLabel: {
      fontSize: RFValue(10),
      lineHeight: RFValue(10),
      fontFamily: 'EuclidCircularA-Medium',
      color: 'white',
    },
    subContentDisableBody: {
      fontSize: RFValue(12),
      lineHeight: RFValue(14),
      fontFamily: 'EuclidCircularA-Regular',
      color: 'primaryDark',
    },
    titleEmptyContent: {
      fontSize: RFValue(14),
      lineHeight: RFValue(18),
      fontFamily: 'EuclidCircularA-Medium',
      color: 'primaryDark',
    },
    contentToastNotification: {
      fontSize: RFValue(14),
      lineHeight: RFValue(18),
      fontFamily: 'EuclidCircularA-Bold',
      color: 'primaryDark',
    },
    subContentBodyLight: {
      fontSize: RFValue(14),
      lineHeight: RFValue(24),
      fontFamily: 'EuclidCircularA-Regular',
      color: 'white',
      maxWidth: RFValue(250),
    },
    sectionTitleLight: {
      fontSize: RFValue(16),
      lineHeight: RFValue(16),
      fontFamily: 'EuclidCircularA-Medium',
      color: 'primaryDarkest',
    },
    personalDataSubtitle: {
      fontSize: RFValue(13),
      lineHeight: RFValue(13),
      fontFamily: 'EuclidCircularA-Regular',
      fontWeight: '400',
      color: 'gray300',
    },
    formTitle: {
      fontSize: RFValue(20),
      lineHeight: RFValue(20),
      fontFamily: 'EuclidCircularA-Bold',
      fontWeight: '600',
    },
    labelCard: {
      fontSize: RFValue(7),
      lineHeight: RFValue(12),
      fontFamily: 'EuclidCircularA-Regular',
      color: 'primaryDarkest',
      maxWidth: RFValue(250),
    },
    headerCard: {
      fontSize: RFValue(23),
      fontWeight: '600',
      fontFamily: 'Outfit-SemiBold',
      lineHeight: RFValue(29),
      color: 'primaryDark',
    },
    subHeaderCard: {
      fontSize: RFValue(15.75),
      lineHeight: RFValue(18.9),
      letterSpacing: 0.16,
      fontWeight: '600',
      fontFamily: 'Outfit-SemiBold',
      color: 'primaryDark',
    },
    smallLabelCard: {
      fontSize: RFValue(11.375),
      fontWeight: '400',
      color: 'primaryDark',
      fontFamily: fonts.outfitRegular,
      lineHeight: RFValue(15.75),
      letterSpacing: 0.16,
    },
  },
  buttonVariants: {
    primary: {
      borderRadius: RFValue(32),
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      padding: 'spacing-s',
    },
    secondary: {
      padding: 'spacing-s',
      color: 'black',
      borderColor: 'gray200',
      overflow: 'hidden',
      borderRadius: RFValue(32),
      justifyContent: 'center',
      alignItems: 'center',
    },
    disabled: {
      borderRadius: RFValue(32),
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      padding: 'spacing-s',
    },
    info: {
      color: 'primaryDarkest',
      borderRadius: RFValue(32),
      borderWidth: 3,
      borderColor: 'info',
      padding: 'spacing-s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    danger: {
      color: 'primaryDarkest',
      borderRadius: RFValue(32),
      borderWidth: 3,
      borderColor: 'info',
      padding: 'spacing-s',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
    },
    outline: {
      color: 'primaryDarkest',
      borderRadius: RFValue(32),
      borderWidth: 3,
      borderColor: 'info',
      padding: 'spacing-s',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
    },
  },
  textInputVariants: {
    disabled: {
      backgroundColor: 'secundaryDisable',
      borderColor: 'primaryLigth',
    },
  },
  gradientColors,
});

export type RebrandingTheme = typeof rebrandingTheme;
